AWSTemplateFormatVersion: '2010-09-09'
Description: Create MSSQL RDS Instance

Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: my-mssql-instance
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: sqlserver-ex
      MasterUsername: adminuser
      MasterUserPassword: YourStrongPassword123
      PubliclyAccessible: true
      DBSubnetGroupName: default-vpc-0ad8852ed8e2c84d9
      VPCSecurityGroups:
        - sg-0fb73d4745d7b1eb6  # Replace with your actual SG ID
      BackupRetentionPeriod: 7
      EngineVersion: 15.00.4390.2.v1
      LicenseModel: license-included
