AWSTemplateFormatVersion: '2010-09-09'
Description: Create MSSQL RDS Instance

Parameters:
  DBInstanceIdentifier:
    Type: String
    Description: RDS instance identifier
    Default: my-mssql-db

Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      AllocatedStorage: 20
      DBInstanceClass: db.t3.medium
      Engine: sqlserver-ex
      MasterUsername: adminuser
      MasterUserPassword: YourStrongPassword123
      PubliclyAccessible: true
      DBSubnetGroupName: default-vpc-0ee588f259ac3df35
      VPCSecurityGroups:
        - sg-070189eb356588ca0  # Replace with your actual SG ID
      BackupRetentionPeriod: 7
      EngineVersion: 15.00.4390.2.v1
      LicenseModel: license-included
