AWSTemplateFormatVersion: '2010-09-09'
Description: Create MSSQL RDS Instance

Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: bdatdp04
      AllocatedStorage: 20
      DBInstanceClass: db.t3.medium
      Engine: sqlserver-ex
      MasterUsername: adminuser
      MasterUserPassword: YourStrongPassword123
      PubliclyAccessible: true
      DBSubnetGroupName: default-vpc-0a33dd853c9acdab7
      VPCSecurityGroups:
        - sg-02fa79a4de69aeeef  # Replace with your actual SG ID
      BackupRetentionPeriod: 7
      EngineVersion: 15.00.4390.2.v1
      LicenseModel: license-included
